import type { NextPage } from 'next'
import Head from 'next/head'
import Layout from '../components/Layout/Layout'
import FilesTree from '../components/FilesTree/FilesTree'
import { FilesTreeData } from '../components/FilesTree/types/types'
import {data_1, data_2} from '../components/FilesTree/stubs/filesTreeStub'

const TREE_STUB_1 = data_1 as FilesTreeData
const TREE_STUB_2 = data_2 as FilesTreeData

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>File Tree</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main>
        <Layout>          
         <FilesTree filesTreeData={TREE_STUB_1}/>
         <FilesTree filesTreeData={TREE_STUB_2}/>
        </Layout>
      </main>
    </div>
  )
}

export default Home
